### ISSUE TITLE
Unicode text in Settings>Personal>Signature doesn't work!

### ISSUE THREAD

**Issue by ConsultingService** [kalkun-sms/Kalkun#208] opened 2020-03-13 15:56 UTC
Unicode text in Kalkun>Settings>Personal>Signature don't work! When you compose the SMS message, the signature gets appended; however, the Unicode characters get converted to "?".

For example, having "Sent by Ēriks Ā." in the signature, will append a signature of "Sent by ?riks ?." when composing a new message.

I tried a few alternate codings for "Ē" and for "Ā", but they don't work either (or I didn't find the correct alternate encoding).

Unicode letters work fine when composing a new SMS message. It's only a problem in the signature setting. You can enter the Unicode letters in the signature box, but when you click on SAVE, Kalkun displays "Your settings has been saved", and the Unicode letters are replaced with "?".

Is there any workaround for getting the Unicode "Ē" and "Ā" to save and work from the signature?

Thx!

**Comment by ConsultingService** [comment] 2020-03-13 16:10
P.S. I'm using Kalkun 0.7.1

**Comment by tenzap** [comment] 2020-04-20 08:21
Can't reproduce. You probably have some misconfiguration somewhere

**Comment by tenzap** [comment] 2022-02-16 19:40
Closing since there is no update from OP for more than a year and can't reproduce in devel.

**Closed by tenzap** 2022-02-16 19:40 UTC
Labels: not-a-bug, configuration-issue
